import React from "react";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import "./InvoiceActions.css";

export default function InvoiceActions({ invoiceRef, customer, totals }) {
  // ---- DOWNLOAD INVOICE AS PDF ----
  const handleDownload = async () => {
    if (!invoiceRef.current) return;

    const element = invoiceRef.current;
    const canvas = await html2canvas(element, { scale: 2 });
    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "mm", "a4");

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = pageWidth;
    const imgHeight = (canvas.height * pageWidth) / canvas.width;

    let position = 0;
    pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);

    // Add footer link
    pdf.setFontSize(10);
    pdf.text(
      "Generated by VedAarna Studio Boutique",
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );

    pdf.save(`VedAarna_Invoice_${customer.name || "Customer"}.pdf`);
  };

  // ---- SEND TO WHATSAPP ----
  const handleWhatsApp = () => {
    const phone = customer.phone?.replace(/[^0-9]/g, "");
    if (!phone) {
      alert("Please enter a valid customer phone number.");
      return;
    }
    const message = `Hello ${customer.name || ""}, here is your invoice from VedAarna Studio.`;
    const url = `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
    window.open(url, "_blank");
  };

  // ---- SEND TO EMAIL ----
  const handleEmail = () => {
    const subject = encodeURIComponent("Your VedAarna Studio Invoice");
    const body = encodeURIComponent(
      `Dear ${customer.name || ""},\n\nPlease find attached your invoice.\n\nThank you,\nVedAarna Studio`
    );
    window.location.href = `mailto:${customer.email}?subject=${subject}&body=${body}`;
  };

  return (
    <div className="invoice-actions">
      <h4>Invoice Actions</h4>
      <button className="btn primary" onClick={handleDownload}>
        💾 Download Invoice
      </button>
      <button className="btn whats" onClick={handleWhatsApp}>
        💬 Send via WhatsApp
      </button>
      <button className="btn email" onClick={handleEmail}>
        ✉️ Send via Email
      </button>
    </div>
  );
}
